---
- name: "Create PKI Directory"
  file:
    path: "{{ cert_directory }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  
- name: "Create private key for CA"
  openssl_privatekey:
    path: "{{ cert_directory }}/{{ ca.key_file }}"

- name: "Create CSR for CA"
  openssl_csr:
    path: "{{ cert_directory }}/{{ ca.csr_file }}"
    privatekey_path: "{{ cert_directory }}/{{ ca.key_file }}"
    common_name: "{{ ca.common_name }}"
    country_name: "{{ ca.country_name }}"
    state_or_province_name: "{{ ca.state_or_province_name }}"
    locality_name: "{{ ca.locality_name }}"
    basic_constraints_critical: true
    basic_constraints:
      - "CA:TRUE"
    key_usage:
      - keyCertSign
      - cRLSign
    extended_key_usage:
      - clientAuth
      - serverAuth

- name: "Generate CA Certificate"
  community.crypto.x509_certificate:
    path: "{{ cert_directory }}/{{ ca.cert_file }}"
    privatekey_path: "{{ cert_directory }}/{{ ca.key_file }}"
    csr_path: "{{ cert_directory }}/{{ ca.csr_file }}"
    provider: selfsigned