certs:
  - key_file: "{{ cert_directory }}/kube-scheduler.key"
    csr_file: "{{ cert_directory }}/kube-scheduler.csr"
    cert_file: "{{ cert_directory }}/kube-scheduler.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    common_name: "system:kube-scheduler"
    ext_usages:
      - clientAuth
    usages:
      - digitalSignature
      - keyEncipherment 