---
- name: Generate Kube Controller Config
  vars:
    component: "controller-manager"
    conf_file: "{{ conf_directory }}/controller-manager.conf"
    credential: default-controller-manager
    ca_cert_file: "{{ cert_directory }}/ca.crt"
    component_key_file: "{{ cert_directory }}/kube-controller-manager.key"
    component_cert_file: "{{ cert_directory }}/kube-controller-manager.crt"
    apiserver_host: "{{ ansible_eth1.ipv4.address }}"
  include_role:
    name: kubeconfig

- name: Create Kube Controller Container
  docker_container:
    name: kube-controller-manager
    image: "public.ecr.aws/eks-distro/kubernetes/kube-controller-manager:v1.21.5-eks-1-21-8"
    restart: yes
    restart_policy: always
    state: started
    volumes:
      - "{{ cert_directory }}:/certs"
      - "{{ conf_directory }}/controller-manager.conf:/controller-manager.conf"
    entrypoint: /usr/local/bin/kube-controller-manager
    command: --kubeconfig /controller-manager.conf --client-ca-file /certs/ca.crt --authentication-kubeconfig /controller-manager.conf --tls-cert-file /certs/kube-controller-manager.bundle --tls-private-key-file /certs/kube-controller-manager.key
    ports:
      - "10252:10252"