---
  - name: "Generate Master Certificate"
    include_role:
      name: ca
      tasks_from: create-cert

  - name: Create Certificate Bundles
    shell: "cat {{ item.cert_file }} {{ item.ca_file }} > {{ item.target }}"
    loop:
      - cert_file: "{{ cert_directory }}/kube-apiserver.crt"
        ca_file: "{{ cert_directory }}/ca.crt"
        target: "{{ cert_directory }}/kube-apiserver.bundle"
      - cert_file: "{{ cert_directory }}/kube-controller-manager.crt"
        ca_file: "{{ cert_directory }}/ca.crt"
        target: "{{ cert_directory }}/kube-controller-manager.bundle"
      - cert_file: "{{ cert_directory }}/kube-scheduler.crt"
        ca_file: "{{ cert_directory }}/ca.crt"
        target: "{{ cert_directory }}/kube-scheduler.bundle"
      - cert_file: "{{ cert_directory }}/kubelet.crt"
        ca_file: "{{ cert_directory }}/ca.crt"
        target: "{{ cert_directory }}/kubelet.bundle"

  - name: Deploy ETCD
    include_tasks: etcd.yml

  - name: Deploy API Server
    include_tasks: apiserver.yml

  - name: Deploy Controller Manager
    include_tasks: controller-manager.yml

  - name: Deploy Scheduler
    include_tasks: scheduler.yml

  - name: Deploy Kubelet
    include_role:
      name: kubelet
  
  - name: Create .kube directory
    file:
      path: /root/.kube
      state: directory
      mode: '0755'

  - name: Generate Admin Kube Config
    vars:
      component: "admin"
      conf_file: "/root/.kube/config"
      credential: default-admin
      ca_cert_file: "{{ cert_directory }}/ca.crt"
      component_key_file: "{{ cert_directory }}/admin.key"
      component_cert_file: "{{ cert_directory }}/admin.crt"
      apiserver_host: "{{ ansible_eth1.ipv4.address }}"
    include_role:
      name: kubeconfig