---
  - name: "Generate Master Certificate"
    include_role:
      name: ca
      tasks_from: create-cert
    loop: "{{ certs }}"
    loop_control:
      loop_var: cert

  - name: Create Certificate Bundles
    shell: "cat {{ item.cert_file }} {{ item.ca_file }} > {{ item.target }}"
    loop:
      - cert_file: "{{ cert_directory }}/kube-apiserver.crt"
        ca_file: "{{ cert_directory }}/ca.crt"
        target: "{{ cert_directory }}/kube-apiserver.bundle"
      - cert_file: "{{ cert_directory }}/kube-controller-manager.crt"
        ca_file: "{{ cert_directory }}/ca.crt"
        target: "{{ cert_directory }}/kube-controller-manager.bundle"
      - cert_file: "{{ cert_directory }}/kube-scheduler.crt"
        ca_file: "{{ cert_directory }}/ca.crt"
        target: "{{ cert_directory }}/kube-scheduler.bundle"

  - name: Deploy ETCD
    include_tasks: etcd.yml

  - name: Deploy API Server
    include_tasks: apiserver.yml

  - name: Deploy Controller Manager
    include_tasks: controller-manager.yml

  - name: Deploy Scheduler
    include_tasks: scheduler.yml