---
- name: Generate Kube Scheduler Config
  vars:
    component: "scheduler"
    conf_file: "{{ conf_directory }}/scheduler.conf"
    credential: default-scheduler
    ca_cert_file: "{{ cert_directory }}/ca.crt"
    component_key_file: "{{ cert_directory }}/kube-scheduler.key"
    component_cert_file: "{{ cert_directory }}/kube-scheduler.crt"
    apiserver_host: "{{ ansible_eth1.ipv4.address }}"
  include_role:
    name: kubeconfig

- name: Create Kube Scheduler Container
  docker_container:
    name: kube-scheduler
    image: "public.ecr.aws/eks-distro/kubernetes/kube-scheduler:v1.21.5-eks-1-21-8"
    restart: yes
    restart_policy: always
    state: started
    volumes:
      - "{{ cert_directory }}:/certs"
      - "{{ conf_directory }}/scheduler.conf:/scheduler.conf"
    entrypoint: /usr/local/bin/kube-scheduler
    command: --kubeconfig /scheduler.conf --client-ca-file /certs/ca.crt --authentication-kubeconfig /scheduler.conf --tls-cert-file /certs/kube-scheduler.bundle --tls-private-key-file /certs/kube-scheduler.key
    ports:
      - "10251:10251"