---
- name: Create SA Signing Key for EKS Distro API Server
  openssl_privatekey:
    path: "/etc/kubernetes/pki/sa.key"

- name: Create SA Public for EKS Distro API Server
  community.crypto.openssl_publickey:
    path: /etc/kubernetes/pki/sa.pub
    privatekey_path: /etc/kubernetes/pki/sa.key

- name: "Generate EKS Distro API Server Certificates"
  include_role:
    name: ca
    tasks_from: create-cert
  loop: "{{ certs }}"
  loop_control:
    loop_var: cert

- name: Create EKS Distro API Server Bundle
  shell: cat /etc/kubernetes/pki/kube-apiserver.crt /etc/kubernetes/pki/ca.crt > /etc/kubernetes/pki/kube-apiserver.bundle

- name: Create API Server Container
  docker_container:
    name: kube-apiserver
    image: "public.ecr.aws/eks-distro/kubernetes/kube-apiserver:v1.21.5-eks-1-21-8"
    restart: yes
    restart_policy: always
    state: started
    volumes:
      - /etc/kubernetes/pki:/certs
    entrypoint: /usr/local/bin/kube-apiserver
    command: --tls-cert-file /certs/kube-apiserver.bundle --tls-private-key-file /certs/kube-apiserver.key --etcd-cafile /certs/ca.crt --etcd-certfile /certs/kube-apiserver-etcd-client.crt --etcd-keyfile /certs/kube-apiserver-etcd-client.key --service-account-signing-key-file /certs/sa.key --service-account-key-file /certs/sa.pub --service-account-issuer kubernetes-ca  --service-cluster-ip-range "{{ pod_network }}" --etcd-servers "https://{{ ansible_eth1.ipv4.address }}:2379" --client-ca-file /certs/ca.crt
    ports:
      - "6443:6443"