certs:
  - key_file: "{{ cert_directory }}/kube-controller-manager.key"
    csr_file: "{{ cert_directory }}/kube-controller-manager.csr"
    cert_file: "{{ cert_directory }}/kube-controller-manager.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    common_name: "system:kube-controller-manager"
    ext_usages:
      - clientAuth
    usages:
      - digitalSignature
      - keyEncipherment 