---
- name: Create PKI Directories
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  loop:
    - /etc/kubernetes
    - /etc/kubernetes/pki

- name: Create private key for EKS Distro CA
  openssl_privatekey:
    path: /etc/kubernetes/pki/ca.key

- name: Create CSR for EKS Distro CA
  openssl_csr:
    path: /etc/kubernetes/pki/ca.csr
    privatekey_path: /etc/kubernetes/pki/ca.key
    common_name: kubernetes-ca
    country_name: GB
    state_or_province_name: Hampshire
    locality_name: Portsmouth
    basic_constraints_critical: true
    basic_constraints:
      - "CA:TRUE"
    key_usage:
      - digitalSignature
      - keyAgreement
    extended_key_usage:
      - clientAuth
      - serverAuth

- name: Generate EKS Distro CA Certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/ca.crt
    privatekey_path: /etc/kubernetes/pki/ca.key
    csr_path: /etc/kubernetes/pki/ca.csr
    provider: selfsigned