---
  - name: Preparing EKS Distro Node
    hosts: localhost
    connection: local 
    tasks:
      - name: Install packages
        include_role: 
          name: base
      - name: Create Certificate Authority
        include_role:
          name: ca
          tasks_from: create-ca