node_name: eksdistro
cert_directory: /etc/kubernetes/pki
pod_network: "172.16.0.0/24"
conf_directory: /etc/kubernetes
certs:
  - key_file: "{{ cert_directory }}/kube-etcd.key"
    csr_file: "{{ cert_directory }}/kube-etcd.csr"
    cert_file: "{{ cert_directory }}/kube-etcd.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    alt_names: 
      - "DNS:localhost"
      - "IP:127.0.0.1"
      - "IP:{{ ansible_eth1.ipv4.address }}"
    ext_usages:
      - clientAuth
      - serverAuth
    usages:
      - digitalSignature
      - keyEncipherment
  - key_file: "{{ cert_directory }}/kube-etcd-peer.key"
    csr_file: "{{ cert_directory }}/kube-etcd-peer.csr"
    cert_file: "{{ cert_directory }}/kube-etcd-peer.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    alt_names:
      - "DNS:localhost"
      - "IP:127.0.0.1"
      - "IP:{{ ansible_eth1.ipv4.address }}"
    ext_usages:
      - clientAuth
      - serverAuth
    usages:
      - digitalSignature
      - keyEncipherment
  - key_file: "{{ cert_directory }}/kube-apiserver-etcd-client.key"
    csr_file: "{{ cert_directory }}/kube-apiserver-etcd-client.csr"
    cert_file: "{{ cert_directory }}/kube-apiserver-etcd-client.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    organization_name: "system:masters"
    ext_usages:
      - clientAuth
    usages:
      - digitalSignature
      - keyEncipherment
  - key_file: "{{ cert_directory }}/kube-apiserver.key"
    csr_file: "{{ cert_directory }}/kube-apiserver.csr"
    cert_file: "{{ cert_directory }}/kube-apiserver.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    alt_names:
      - "DNS:localhost"
      - "IP:127.0.0.1"
      - "IP:{{ ansible_eth1.ipv4.address }}"
    ext_usages:
      - serverAuth
    usages:
      - digitalSignature
      - keyEncipherment
  - key_file: "{{ cert_directory }}/kube-controller-manager.key"
    csr_file: "{{ cert_directory }}/kube-controller-manager.csr"
    cert_file: "{{ cert_directory }}/kube-controller-manager.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    common_name: "system:kube-controller-manager"
    ext_usages:
      - clientAuth
    usages:
      - digitalSignature
      - keyEncipherment 
  - key_file: "{{ cert_directory }}/kube-scheduler.key"
    csr_file: "{{ cert_directory }}/kube-scheduler.csr"
    cert_file: "{{ cert_directory }}/kube-scheduler.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    common_name: "system:kube-scheduler"
    ext_usages:
      - clientAuth
    usages:
      - digitalSignature
      - keyEncipherment 
  - key_file: "{{ cert_directory }}/kubelet.key"
    csr_file: "{{ cert_directory }}/kubelet.csr"
    cert_file: "{{ cert_directory }}/kubelet.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    common_name: "system:node:{{ node_name }}"
    organization_name: "system:nodes"
    ext_usages:
      - clientAuth
    usages:
      - digitalSignature
      - keyEncipherment 
  - key_file: "{{ cert_directory }}/admin.key"
    csr_file: "{{ cert_directory }}/admin.csr"
    cert_file: "{{ cert_directory }}/admin.crt"
    ca_file:  "{{ cert_directory }}/ca.crt"
    ca_key_file:  "{{ cert_directory }}/ca.key"
    common_name: "kubernetes-admin"
    organization_name: "system:masters"
    ext_usages:
      - clientAuth
    usages:
      - digitalSignature
      - keyEncipherment 